### ISSUE TITLE
CORS Setup for Prod

### ISSUE THREAD

**Issue by exvertus** [kevwhuang/atxproducers#12]
### Goal
Lock down CORS for production to trusted domains only.

### Tasks

- [ ] **Check Current CORS Setup**
  - Make sure we're not allowing all origins (`*`).

- [ ] **List Trusted Domains**
  - Identify which domains should have access.

- [ ] **Configure CORS for Trusted Domains**
  - Use `cors` package in Express:
    ```
    app.use(cors({
      origin: ['https://www.ourfrontend.com', 'https://www.partnerapi.com'],
    }));
    ```

- [ ] **Test CORS**
  - Try requests from non-listed domains to ensure they're blocked.
  - Confirm requests from allowed domains work fine.

- [ ] **Adjust Allowed HTTP Methods**
  - Check and set which methods (GET, POST, etc.) are okay.

- [ ] **Credentials Support**
  - Set `credentials: true` if your frontend needs to send cookies or auth headers.

- [ ] **Set Exposed Headers**
  - Specify if any custom headers need to be accessible to the frontend.

- [ ] **Update Docs**
  - Document the CORS changes and reasons.

- [ ] **Inform Team**
  - Let frontend and any partners know about the CORS setup.

### Done When
- Only listed domains can access our backend.
- CORS policy is clear in docs and known to the team.
